### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by Thinking80s** [vivaxy/gacp#73]
localhost:~ kevin$ nvm use 6.5.0
Now using node v6.5.0 (npm v6.11.3)
localhost:~ kevin$ gacp
/Users/kevin/.nvm/versions/node/v6.5.0/lib/node_modules/gacp/lib/bin.js:19
async function configureYargs() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by vivaxy** [comment]
gacp requires node.js > v10.
@Thinking80s You can try to use gacp@2.0
